---
title: "Response by Station"
author: "T. Poole"
date: '2022-05-06'
output: html_document
---


## SBFD Response Time Analysis of 5 Residental Occupancys

This is a look at response time for by Ladder 1 and Engine 2 to six frequent
occupancys. 


```{r,echo=FALSE,include=FALSE}
library(tidyverse)
```

```{r}
## Load Data from csv and create data frames#

####   Import data and remove non-essential fields/variables ####

                Pivot_Table_2016_2021.df <- read.csv(file = "pivot20162021.csv",header = TRUE, na.strings=c("", "NA"),sep = ",")
                Unitresp20102021.df <- read.csv(file = "unitresp20102021.csv",header = TRUE, na.strings=c("", "NA"),sep = ",")
        
                ## Left join both df above ##
                
                        Left_joinedpivotresp.df <- left_join(Pivot_Table_2016_2021.df,Unitresp20102021.df, by = "inci_no")
                        
####   Build new data frame and filter for 465 Quarryhill, 90 Allen road, 1510-1530 Williston, 20 Harborview ####
        
                Frequent_healthcare.df <- Left_joinedpivotresp.df %>%
                        select(inci_no,station,number,street,resp,unit_desc) %>%
                        filter(number %in% c("90","20","1510","465","310","1530"),street %in% c("Williston","Quarryhill", "Allen", "Anderson","Harborview","Market"))
                
```


```{r}
  ## 1510 and 1530 Williston Rd., Ladder1 responses (Gazebo_ladder1.df) ##
                
                Gazebo_ladder1.df <- Frequent_healthcare.df %>% 
                       filter(number %in% c("1510","1530"), street %in% c("Williston"), unit_desc %in% c("Ladder 1"))
                        summary(Gazebo_ladder1.df$resp)
                        
                        hist(Gazebo_ladder1.df$resp, breaks = 15, main = "Ladder 1 respones to 1510 / 1530 Williston rd",xlab = "Seconds")
                        abline(v=c(mean(Gazebo_ladder1.df$resp),median(Gazebo_ladder1.df$resp)),lty=c(2,3),lwd=2)
                        legend("topright",legend = c("mean","median"),lty=c(2,3),lwd = 2)
                       
                        boxplot(Gazebo_ladder1.df$resp,main="Ladder 1 response to 1510 or 1530 Williston rd.",xlab = "", ylab = "Seconds")
                        abline(h=c(300),col="red",lty=4, lwd=2)
                        
                        
                ## 1510 and 1530 Williston Rd., Engine2 responses (Gazebo_engine2.df) ##
                
                Gazebo_engine2.df <- Frequent_healthcare.df %>% 
                        filter(number %in% c("1510","1530"), street %in% c("Williston"), unit_desc %in% c("Engine 2"))
                        summary(Gazebo_engine2.df$resp)
                
```

